### PR TITLE
Timer fixed

### LINKED ISSUE #3: Game timer should run when the level is interactive
The idea of having a timer is to force players to think quickly, so it should be running as they manipulate the level, and should stop when the simulation is running.

### PR DESCRIPTION
**Pull request by yicyao**
closed #3

### CODE REVIEW

File: oprheum-game/MenuScene.swift [hunk 1]
```diff
@@ -3,7 +3,7 @@
 //
 //  Copyright © 2016 Yichen Yao, Elizabeth Singer, Hadley Shapland. All rights reserved.
 //
-
+//	2048px by 1536px
```
Comment (clayreimann) [inline oprheum-game/MenuScene.swift]: what is this?

File: oprheum-game/SnowballScene.swift [hunk 2]
```diff
@@ -2,8 +2,7 @@
 //  GameScene.swift
 //
 //  Copyright © 2016 Yichen Yao, Elizabeth Singer, Hadley Shapland. All rights reserved.
-//
-
+//restarting simulator, restart computer, download new xcode
```
Comment (clayreimann) [inline oprheum-game/SnowballScene.swift]: And this?

File: oprheum-game/SnowballScene.swift [hunk 3]
```diff
@@ -24,17 +23,23 @@ class SnowballScene: SKScene {
...
-        start = nil
+        start = NSDate()
     }
 
     func startSimulation() {
         self.physicsWorld.speed = 1.0
-        start = NSDate()
+        if let start = start {
+            let delta = start.timeIntervalSinceReferenceDate - NSDate().timeIntervalSinceReferenceDate
+//print("\(start) \(start.timeIntervalSinceReferenceDate) \(start.timeIntervalSinceNow) \(NSDate().timeIntervalSinceReferenceDate)")
```
Comment (clayreimann) [inline oprheum-game/SnowballScene.swift]: Do you still need this line?

File: oprheum-game/SnowballScene.swift [hunk 4]
```diff
@@ -281,7 +294,6 @@ class SnowballScene: SKScene {
     }
 
     func handlePinchGesture(recognizer: UIPinchGestureRecognizer) {
-        // let center = recognizer.locationInView(self.view!)
```
Comment (clayreimann) [inline oprheum-game/SnowballScene.swift:284]: Do you need this line?

**Review by clayreimann — CHANGES_REQUESTED** [review]
Questions for you.

**Review by clayreimann — APPROVED** [review]
