### PR TITLE
fixes reset

### LINKED ISSUE #63: reset scene after win

### PR DESCRIPTION
**Pull request by yicyao**
resets ramp + snowball after win
close #63

### CODE REVIEW

File: oprheum-game/SnowballScene.swift [hunk 1]
```diff
@@ -298,6 +298,8 @@ class SnowballScene: BaseScene {
 
             addGameObjectsToScene()
             resetScene()
+            snowballNode.redrawSnowball()
+            rampNode.redrawTriangle(200, height: 200)
```
Comment (clayreimann) [inline oprheum-game/SnowballScene.swift]: You should use `RampNode.initialSize` here.

File: oprheum-game/SnowballScene.swift [hunk 2]
```diff
@@ -298,6 +298,8 @@ class SnowballScene: BaseScene {
 
             addGameObjectsToScene()
             resetScene()
+            snowballNode.redrawSnowball()
```
Comment (clayreimann) [inline oprheum-game/SnowballScene.swift]: Don't you need to reset the snowball's mass first?

**Review by clayreimann — CHANGES_REQUESTED** [review]

**Review by clayreimann — APPROVED** [review]
